In [ ]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report


def evaluate_model(X, y, dataset_name):
    print(f"\n========== {dataset_name} ==========")

    # Train-Test Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42
    )

    # ID3 (Entropy-based Decision Tree)
    model = DecisionTreeClassifier(criterion="entropy", random_state=42)
    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    print("Accuracy :", round(acc, 4))
    print("Precision:", round(prec, 4))
    print("Recall   :", round(rec, 4))
    print("F1 Score :", round(f1, 4))

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    return acc, prec, rec, f1


iris = load_iris()
X_iris = iris.data
y_iris = iris.target

iris_metrics = evaluate_model(X_iris, y_iris, "Iris Dataset")


cancer = load_breast_cancer()
X_cancer = cancer.data
y_cancer = cancer.target

cancer_metrics = evaluate_model(X_cancer, y_cancer, "Breast Cancer Dataset")


comparison = pd.DataFrame({
    "Dataset": ["Iris", "Breast Cancer"],
    "Accuracy": [iris_metrics[0], cancer_metrics[0]],
    "Precision": [iris_metrics[1], cancer_metrics[1]],
    "Recall": [iris_metrics[2], cancer_metrics[2]],
    "F1 Score": [iris_metrics[3], cancer_metrics[3]]
})

print("\n========== Performance Comparison ==========")
print(comparison)


========== Iris Dataset ==========
Accuracy : 0.9778
Precision: 0.9794
Recall   : 0.9778
F1 Score : 0.9777

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  1 12]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      1.00      0.96        13
           2       1.00      0.92      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45


========== Breast Cancer Dataset ==========
Accuracy : 0.9649
Precision: 0.965
Recall   : 0.9649
F1 Score : 0.9648

Confusion Matrix:
[[ 59   4]
 [  2 106]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.94      0.95        63
           1       0.96      0.98      0.97       108

    accuracy                           0.96       171
   macro avg       0.97      0.

In [ ]:
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_california_housing, load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


def evaluate_regression_model(X, y):

    # Train-Test Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42
    )

    # CART Regressor (MSE-based)
    model = DecisionTreeRegressor(
        criterion="squared_error",   # CART uses MSE
        random_state=42,
        max_depth = 10
    )

    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)

    # Metrics
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print("MSE  :", round(mse, 4))
    print("RMSE :", round(rmse, 4))
    print("MAE  :", round(mae, 4))
    print("R2   :", round(r2, 4))

    return mse, rmse, mae, r2


california = fetch_california_housing()
X_cal = california.data
y_cal = california.target

cal_metrics = evaluate_regression_model(X_cal, y_cal)


diabetes = load_diabetes()
X_diab = diabetes.data
y_diab = diabetes.target

diab_metrics = evaluate_regression_model(X_diab, y_diab)


# ======================
# Comparison Table
# ======================
comparison = pd.DataFrame({
    "Dataset": ["California Housing", "Diabetes"],
    "MSE": [cal_metrics[0], diab_metrics[0]],
    "RMSE": [cal_metrics[1], diab_metrics[1]],
    "MAE": [cal_metrics[2], diab_metrics[2]],
    "R2 Score": [cal_metrics[3], diab_metrics[3]]
})

print("\n========== CART Performance Comparison ==========")
print(comparison)

MSE  : 0.4156
RMSE : 0.6447
MAE  : 0.4286
R2   : 0.6834
MSE  : 5206.9111
RMSE : 72.1589
MAE  : 56.5943
R2   : 0.0355

========== CART Performance Comparison ==========
              Dataset          MSE       RMSE        MAE  R2 Score
0  California Housing     0.415577   0.644653   0.428594  0.683379
1            Diabetes  5206.911069  72.158929  56.594319  0.035455
