In [ ]:
!pip install ucimlrepo

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Classification (Car Evaluation)

In [ ]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

# sklearn imports
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score,confusion_matrix

# fetch dataset
car_evaluation = fetch_ucirepo(id=19)

# features and target
X = car_evaluation.data.features
y = car_evaluation.data.targets

# convert categorical variables to numeric using Label Encoding
le = LabelEncoder()

for col in X.columns:
    X[col] = le.fit_transform(X[col])

y = y.apply(le.fit_transform)

# split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# create Random Forest model
rf = RandomForestClassifier(n_estimators=100, random_state=42)

# train model
rf.fit(X_train, y_train.values.ravel())

# predictions
y_pred = rf.predict(X_test)

# evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

# results
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)




# compute confusion matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:\n", cm)


/tmp/ipykernel_738/3153883089.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_738/3153883089.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_738/3153883089.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guid

Accuracy: 0.9739884393063584
Precision: 0.9798913856439202
Recall: 0.9739884393063584
F1 Score: 0.9752422823939135
Confusion Matrix:
 [[ 75   6   2   0]
 [  0  11   0   0]
 [  0   0 235   0]
 [  1   0   0  16]]


# Regression (Abalone Dataset)

In [ ]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

# sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# fetch dataset
abalone = fetch_ucirepo(id=1)

# features and target
X = abalone.data.features
y = abalone.data.targets

# encode categorical feature (Sex)
le = LabelEncoder()
X['Sex'] = le.fit_transform(X['Sex'])

# split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Random Forest Regressor
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# train model
rf.fit(X_train, y_train.values.ravel())

# predictions
y_pred = rf.predict(X_test)

# evaluation metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)
print("R2 Score:", r2)

/tmp/ipykernel_738/3043515402.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Sex'] = le.fit_transform(X['Sex'])


Mean Squared Error (MSE): 5.0914521531100485
Mean Absolute Error (MAE): 1.5899282296650716
R2 Score: 0.5296671259326307
